### ISSUE TITLE
Product Module bugs

### ISSUE THREAD

**Issue by KageyamaJie** [KageyamaJie/Pfizer-Pharmacy#11]
Bug 1: Product Price format

One of the constant problem that user will make is the numbering formatting, price is a numeric format with any character in between price format. Sometimes the user will key in character in accidentally. If the character being key into price field, it will resulting in the database side that there is a data type being compromised as character or string cannot compact with double data type.

Bug 2: Missed out essential data

In the product module’s create module, all the data are require to enter in the field in order the control tier can get the data from the interface pass into domain part. Sometime, the user will missed out one essential detail need to key in. For example, the user want to register a product, after fill in the detail, the user forget to enter the product’s name after click on the “registration”, so in the database side, there is a product record that leave the product’s name blank or null.

**Comment by ckming94** [comment]
Solution for Bug 1:
The only solution is providing two text field for user to enter the price of the product, each of these 2 text field will be restrict and limit user input the character, so that once the user accidentally press on the character from the key broad, the text field will not accept any character but numeric.  

Solution for Bug 2:
To overcome this problem, the system should check each of the text field whether the data is entered using .isEmpty() method. If the user did not enter the data in that field after press on the “Register” button, the system will prompt an message to user and require the user to enter the data in that field that leave blank.

**Comment by KageyamaJie** [comment]
Alright, thanks for the solutions!
